### PR TITLE
Bug fix: parsing the css files would put the result in the same entry…

### PR DESCRIPTION
**Pull request by yoel-zeldes**
… of sheets var. Solved by using IIFE.

### CODE REVIEW

**Comment by retallicka** [comment]
@yoel-zeldes I was only getting viewport units converted and rules added to the head from the last CSS file loaded. This fixed my problem, thanks

**Comment by monolux** [comment]
@yoel-zeldes & @retallicka How can I merge this commit with [my fork](https://github.com/monolux/vminpoly) please? New to GitHub and would like to merge this commit with my fork instead of copying and pasting the changes from the commit line by line. Thank you.

**Comment by yoel-zeldes** [comment]
@saabi is there a reason not to merge this pull request?

**Comment by saabi** [comment]
I have no time to maintain the repo lately and all merges are held up waiting for #39 but this one is important enough that it should be merged.

If anybody wants to help out just mention it, I'm sure he'll be more than welcome by a lot of people.

First thing on the list would be to resolve conflicts on #39.

**Pull request merged**
